"""empty message

Revision ID: dfe3bdd5a22f
Revises: 9d1ab8523435
Create Date: 2020-04-28 18:04:48.652274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe3bdd5a22f'
down_revision = '9d1ab8523435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_show_id_fkey', 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show_id')
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.drop_constraint('Venue_show_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_show_id_fkey', 'Venue', 'Show', ['show_id'], ['id'])
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    op.add_column('Artist', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Artist_show_id_fkey', 'Artist', 'Show', ['show_id'], ['id'])
    # ### end Alembic commands ###
